In [5]:
import numpy as np
import pandas as pd
X = pd.read_csv('C:\\Users\\usmanzafar\\Desktop\\refinedperm.csv')
# limit to categorical data using df.select_dtypes()
X = X.select_dtypes(include=[object])
X['pw_amount_9089'] = X['pw_amount_9089'].str.replace(',', '')
X=X.dropna(how='any') 
X.to_csv('C:\\Users\\usmanzafar\\Downloads\\refinedperm.csv',index=False, encoding = 'utf-8')

C:\Users\usmanzafar\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [6]:
X = pd.read_csv('C:\\Users\\usmanzafar\\Downloads\\refinedperm.csv')

In [7]:
X.shape

(94122, 16)

In [8]:
X.case_status.unique()
X.case_status.value_counts()

Certified            40995
Certified-Expired    40002
Denied                7130
Withdrawn             5995
Name: case_status, dtype: int64

In [9]:
# TODO: create a LabelEncoder object and fit it to each feature in X
# 1. INSTANTIATE
# encode labels with value between 0 and n_classes-1.
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
# 2/3. FIT AND TRANSFORM
# use df.apply() to apply le.fit_transform to all columns
X_2 = X.apply(le.fit_transform)
X_2.head()
X_2.reset_index(drop=True)
X_2.case_status.unique()

array([1, 0, 2, 3], dtype=int64)

In [10]:
from sklearn.preprocessing import LabelEncoder

enc = LabelEncoder()
label_encoder = enc.fit(X_2['case_status'])
print ("Categorical classes:", label_encoder.classes_)
integer_classes = label_encoder.transform(label_encoder.classes_)
print ("Integer classes:", integer_classes)
x_train = label_encoder.transform(X_2['case_status'])

Categorical classes: [0 1 2 3]
Integer classes: [0 1 2 3]


In [11]:
x_train = x_train[:,np.newaxis]
print(x_train)

[[1]
 [1]
 [1]
 ..., 
 [0]
 [3]
 [0]]


In [12]:
X_2.reset_index(drop=True)

case_status  class_of_admission  decision_date  employer_address_1  \
0                1                  17            118               23647   
1                1                  17            130               20190   
2                1                  28            136               23556   
3                1                  17            127                4296   
4                1                  17            110                 507   
5                1                  17            121                 613   
6                0                  17            152                8881   
7                1                  17            105                 709   
8                1                  17            114                 824   
9                1                  17            121                 475   
10               1                  17             90               18332   
11               1                  17             92               19106   
12               1                  17             72                 501   
13               1                  28            137               23556   
14               1                  17            131               23556   
15               1                  17             93               23470   
16               1                  17             85               13832   
17               1                  17            133               15425   
18               1                  17             92                3300   
19               1                  17             90                 264   
20               1                  17             84                 709   
21               1                  17             82               18980   
22               0                  17            148                4319   
23               0                  17            187               19265   
24               1                  17            135                1205   
25               1                  17             95               20728   
26               1                  17            115                5903   
27               1                  17             75                5900   
28               1                  17             75                7043   
29               1                  17             77                5145   
...            ...                 ...            ...                 ...   
94092            0                  17            544               18994   
94093            0                  28            525               17647   
94094            0                  46            523               18203   
94095            0                  17            513                8453   
94096            0                  17            509               14381   
94097            0                  17            509                5601   
94098            0                  17            509                5601   
94099            0                  17            509                8453   
94100            0                  28            523               11017   
94101            0                  17            501               15766   
94102            0                  17            544               21339   
94103            0                  17            528               12815   
94104            0                  17            532                1581   
94105            0                  17            549               14435   
94106            0                  17            560               11910   
94107            0                  17            565                9698   
94108            0                  17            546               18871   
94109            0                  33            567               15709   
94110            0                  17            567               19274   
94111            0                  17            565               14542   
941

In [13]:
features=np.asmatrix(X_2)

In [14]:
print(features)

[[  1  17 118 ..., 566   3   4]
 [  1  17 130 ...,   1   3   4]
 [  1  28 136 ..., 563   3   4]
 ..., 
 [  0  17 560 ..., 505   3   4]
 [  3  17 546 ..., 127   3   4]
 [  0  17 562 ..., 118   3   4]]


In [15]:
x_train.shape

(94122, 1)

In [16]:

b= x_train.reshape(94122,)

In [17]:
b.shape
print(b)

[1 1 1 ..., 0 3 0]


In [24]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from imblearn.ensemble import BalancedBaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
X2_train, X2_test, y2_train, y2_test = train_test_split(features, b, random_state=0)  

clf1 = LogisticRegression()
clf2 = GaussianNB()
clf3 = tree.DecisionTreeClassifier()
clf4 = RandomForestClassifier(n_estimators = 18)
clf5 = MLPClassifier(alpha = 1)
clf6 = KNeighborsClassifier()
clf7 = SVC()
clf8 = GradientBoostingClassifier()

bbc = BalancedBaggingClassifier(base_estimator=clf1,
                                 ratio='auto',
                                 replacement=False,
                                 random_state=0)

bbc.fit(features, b) 
y_pred = bbc.predict(X2_test)

##printing the results fro random forest classifier 
print("******************************************************************8")
print("results for balanced bagging classifier with logistic regression classifier! ")
print (classification_report_imbalanced(y2_test, y_pred))
print ("confusion matrix for balanced bagging classifier with logistic regression classifier! ")
print(confusion_matrix(y2_test, y_pred))
print("")

******************************************************************8
results for balanced bagging classifier with logistic regression classifier! 
                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      1.00      1.00      1.00      1.00     10213
          1       0.96      0.87      0.97      0.92      0.94      0.88     10110
          2       0.50      0.76      0.94      0.60      0.70      0.47      1719
          3       0.95      0.98      1.00      0.97      0.97      0.94      1489

avg / total       0.94      0.93      0.98      0.93      0.95      0.91     23531

confusion matrix for balanced bagging classifier with logistic regression classifier! 
[[10213     0     0     0]
 [    8  8822  1280     0]
 [    0   338  1302    79]
 [    0     0    23  1466]]



In [25]:
bbc = BalancedBaggingClassifier(base_estimator=clf2,
                                 ratio='auto',
                                 replacement=False,
                                 random_state=0)
bbc.fit(features, b) 
y_pred = bbc.predict(X2_test)
print ("******************************************************************")
print("results for balanced bagging classifier with Naive Bayes gaussian NB classifier! ")
print (classification_report_imbalanced(y2_test, y_pred))
print("confusion matrix for balanced bagging classifier with Naive Bayes gaussian NB classifier! ")
print(confusion_matrix(y2_test, y_pred))
print("")


******************************************************************
results for balanced bagging classifier with Naive Bayes gaussian NB classifier! 
                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      1.00      1.00      1.00      1.00     10213
          1       1.00      0.99      1.00      0.99      1.00      0.99     10110
          2       0.93      1.00      0.99      0.96      0.96      0.92      1719
          3       1.00      0.98      1.00      0.99      1.00      1.00      1489

avg / total       0.99      0.99      1.00      0.99      1.00      0.99     23531

confusion matrix for balanced bagging classifier with Naive Bayes gaussian NB classifier! 
[[10213     0     0     0]
 [    0 10007   103     0]
 [    0     0  1719     0]
 [    0     0    26  1463]]



In [32]:
bbc = BalancedBaggingClassifier(base_estimator=clf3,
                                 ratio='auto',
                                 replacement=False,
                                 random_state=0)
bbc.fit(features, b) 
y_pred = bbc.predict(X2_test)
print ("******************************************************************")
print("results for balanced bagging classifier with decision tree classifier! ")
print (classification_report_imbalanced(y2_test, y_pred))
print("confusion matrix for balanced bagging classifier with decision tree classifier! ")
print(confusion_matrix(y2_test, y_pred))
print("")


******************************************************************
results for balanced bagging classifier with decision tree classifier! 
                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      1.00      1.00      1.00      1.00     10213
          1       1.00      1.00      1.00      1.00      1.00      1.00     10110
          2       1.00      1.00      1.00      1.00      1.00      1.00      1719
          3       1.00      1.00      1.00      1.00      1.00      1.00      1489

avg / total       1.00      1.00      1.00      1.00      1.00      1.00     23531

confusion matrix for balanced bagging classifier with decision tree classifier! 
[[10213     0     0     0]
 [    0 10110     0     0]
 [    0     0  1719     0]
 [    0     0     0  1489]]



In [36]:
bbc = BalancedBaggingClassifier(base_estimator=clf4,
                                 ratio='auto',
                                 replacement=False,
                                 random_state=0)
bbc.fit(features, b) 
y_pred = bbc.predict(X2_test)

print ("******************************************************************")
print("results for balanced bagging classifier with random forest classifier! ")
print (classification_report_imbalanced(y2_test, y_pred))
print(" confusion matrix for balanced bagging classifier with  random forest classifie! ")
print(confusion_matrix(y2_test, y_pred))
print("")

******************************************************************
results for balanced bagging classifier with random forest classifier! 
                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      1.00      1.00      1.00      1.00     10213
          1       1.00      1.00      1.00      1.00      1.00      1.00     10110
          2       1.00      1.00      1.00      1.00      1.00      1.00      1719
          3       1.00      1.00      1.00      1.00      1.00      1.00      1489

avg / total       1.00      1.00      1.00      1.00      1.00      1.00     23531

 confusion matrix for balanced bagging classifier with  random forest classifie! 
[[10213     0     0     0]
 [    0 10110     0     0]
 [    0     0  1719     0]
 [    0     0     0  1489]]



In [34]:
bbc = BalancedBaggingClassifier(base_estimator=clf5,
                                 ratio='auto',
                                 replacement=False,
                                 random_state=0)
bbc.fit(features, b) 
y_pred = bbc.predict(X2_test)

print ("******************************************************************")
print("results for balanced bagging classifier with MultiLayer Perceptron! ")
print (classification_report_imbalanced(y2_test, y_pred))
print("confusion matrix for balanced bagging classifier with MultiLayer Perceptron classifier! ")
print(confusion_matrix(y2_test, y_pred))
print("")

******************************************************************
results for balanced bagging classifier with MultiLayer Perceptron! 
                   pre       rec       spe        f1       geo       iba       sup

          0       0.73      0.53      0.85      0.61      0.71      0.51     10213
          1       0.61      0.33      0.84      0.43      0.62      0.38     10110
          2       0.19      0.36      0.88      0.24      0.42      0.16      1719
          3       0.14      0.67      0.71      0.23      0.36      0.12      1489

avg / total       0.60      0.44      0.84      0.48      0.63      0.41     23531

confusion matrix for balanced bagging classifier with MultiLayer Perceptron classifier! 
[[5440 1735 1173 1865]
 [1731 3303 1288 3788]
 [ 234  193  614  678]
 [  91  171  223 1004]]



In [35]:
bbc = BalancedBaggingClassifier(base_estimator=clf6,
                                 ratio='auto',
                                 replacement=False,
                                 random_state=0)
bbc.fit(features, b) 
y_pred = bbc.predict(X2_test)

print ("******************************************************************")
print("results for balanced bagging classifier with K nearest Neighbor! ")
print (classification_report_imbalanced(y2_test, y_pred))
print(" confusion matrix for balanced bagging classifier with K nearest neighbor classifier! ")
print(confusion_matrix(y2_test, y_pred))
print("")

******************************************************************
results for balanced bagging classifier with K nearest Neighbor! 
                   pre       rec       spe        f1       geo       iba       sup

          0       0.64      0.39      0.84      0.48      0.64      0.41     10213
          1       0.66      0.43      0.83      0.52      0.66      0.44     10110
          2       0.23      0.65      0.82      0.34      0.47      0.20      1719
          3       0.15      0.59      0.77      0.24      0.38      0.13      1489

avg / total       0.59      0.44      0.83      0.47      0.62      0.39     23531

 confusion matrix for balanced bagging classifier with K nearest neighbor classifier! 
[[3957 1854 1907 2495]
 [1838 4358 1698 2216]
 [ 162  167 1119  271]
 [ 197  195  220  877]]



In [31]:
from imblearn.ensemble import BalancedBaggingClassifier
from sklearn.ensemble import GradientBoostingClassifier
clf8 = GradientBoostingClassifier()
bbc = BalancedBaggingClassifier(base_estimator=clf8,
                                 ratio='auto',
                                 replacement=False,
                                 random_state=0)
bbc.fit(features, b) 
y_pred = bbc.predict(X2_test)

print ("******************************************************************")
print("results for balanced bagging classifier with Gradient boosting classifier! ")
print (classification_report_imbalanced(y2_test, y_pred))
print("confusion matrix for balanced bagging classifier with grading boosting classifier! ")
print(confusion_matrix(y2_test, y_pred))
print("")

******************************************************************
results for balanced bagging classifier with Gradient boosting classifier! 
                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      1.00      1.00      1.00      1.00     10213
          1       1.00      1.00      1.00      1.00      1.00      1.00     10110
          2       1.00      1.00      1.00      1.00      1.00      1.00      1719
          3       1.00      1.00      1.00      1.00      1.00      1.00      1489

avg / total       1.00      1.00      1.00      1.00      1.00      1.00     23531

confusion matrix for balanced bagging classifier with grading boosting classifier! 
[[10213     0     0     0]
 [    0 10110     0     0]
 [    0     0  1719     0]
 [    0     0     0  1489]]

