In [1]:
import numpy as np
import pandas as pd
X = pd.read_csv('C:\\Users\\usmanzafar\\Desktop\\refinedperm.csv')
# limit to categorical data using df.select_dtypes()
X = X.select_dtypes(include=[object])
X['pw_amount_9089'] = X['pw_amount_9089'].str.replace(',', '')
X=X.dropna(how='any') 
X.to_csv('C:\\Users\\usmanzafar\\Downloads\\refinedperm.csv',index=False, encoding = 'utf-8')

C:\Users\usmanzafar\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [2]:
X = pd.read_csv('C:\\Users\\usmanzafar\\Downloads\\refinedperm.csv')

In [3]:
X.shape

(94122, 16)

In [4]:
X.case_status.unique()
X.case_status.value_counts()

Certified            40995
Certified-Expired    40002
Denied                7130
Withdrawn             5995
Name: case_status, dtype: int64

In [5]:
# TODO: create a LabelEncoder object and fit it to each feature in X
# 1. INSTANTIATE
# encode labels with value between 0 and n_classes-1.
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
# 2/3. FIT AND TRANSFORM
# use df.apply() to apply le.fit_transform to all columns
X_2 = X.apply(le.fit_transform)
X_2.head()
X_2.reset_index(drop=True)
X_2.case_status.unique()

array([1, 0, 2, 3], dtype=int64)

In [6]:
from sklearn.preprocessing import LabelEncoder

enc = LabelEncoder()
label_encoder = enc.fit(X_2['case_status'])
print ("Categorical classes:", label_encoder.classes_)
integer_classes = label_encoder.transform(label_encoder.classes_)
print ("Integer classes:", integer_classes)
x_train = label_encoder.transform(X_2['case_status'])

Categorical classes: [0 1 2 3]
Integer classes: [0 1 2 3]


In [7]:
x_train = x_train[:,np.newaxis]
print(x_train)

[[1]
 [1]
 [1]
 ..., 
 [0]
 [3]
 [0]]


In [8]:
X_2.reset_index(drop=True)

case_status  class_of_admission  decision_date  employer_address_1  \
0                1                  17            118               23647   
1                1                  17            130               20190   
2                1                  28            136               23556   
3                1                  17            127                4296   
4                1                  17            110                 507   
5                1                  17            121                 613   
6                0                  17            152                8881   
7                1                  17            105                 709   
8                1                  17            114                 824   
9                1                  17            121                 475   
10               1                  17             90               18332   
11               1                  17             92               19106   
12               1                  17             72                 501   
13               1                  28            137               23556   
14               1                  17            131               23556   
15               1                  17             93               23470   
16               1                  17             85               13832   
17               1                  17            133               15425   
18               1                  17             92                3300   
19               1                  17             90                 264   
20               1                  17             84                 709   
21               1                  17             82               18980   
22               0                  17            148                4319   
23               0                  17            187               19265   
24               1                  17            135                1205   
25               1                  17             95               20728   
26               1                  17            115                5903   
27               1                  17             75                5900   
28               1                  17             75                7043   
29               1                  17             77                5145   
...            ...                 ...            ...                 ...   
94092            0                  17            544               18994   
94093            0                  28            525               17647   
94094            0                  46            523               18203   
94095            0                  17            513                8453   
94096            0                  17            509               14381   
94097            0                  17            509                5601   
94098            0                  17            509                5601   
94099            0                  17            509                8453   
94100            0                  28            523               11017   
94101            0                  17            501               15766   
94102            0                  17            544               21339   
94103            0                  17            528               12815   
94104            0                  17            532                1581   
94105            0                  17            549               14435   
94106            0                  17            560               11910   
94107            0                  17            565                9698   
94108            0                  17            546               18871   
94109            0                  33            567               15709   
94110            0                  17            567               19274   
94111            0                  17            565               14542   
941

In [9]:
features=np.asmatrix(X_2)

In [10]:
print(features)

[[  1  17 118 ..., 566   3   4]
 [  1  17 130 ...,   1   3   4]
 [  1  28 136 ..., 563   3   4]
 ..., 
 [  0  17 560 ..., 505   3   4]
 [  3  17 546 ..., 127   3   4]
 [  0  17 562 ..., 118   3   4]]


In [11]:
x_train.shape

(94122, 1)

In [12]:

b= x_train.reshape(94122,)

In [13]:
b.shape
print(b)

[1 1 1 ..., 0 3 0]


In [14]:
# Using gaussaian NB on the dataset
from sklearn import svm
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
scores = cross_val_score(clf, features, b, cv=10)
scores

array([ 0.99235182,  0.99139579,  0.99266971,  0.9961755 ,  0.99606927,
        0.99702476,  0.99734353,  0.99723728,  0.99681224,  0.9956434 ])

In [15]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
# Accuracy is hundred percent

Accuracy: 1.00 (+/- 0.00)


In [16]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import time
 
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, LabelEncoder
 
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

In [17]:
from sklearn import svm
from sklearn.model_selection import cross_val_score
clf = KNeighborsClassifier()
scores = cross_val_score(clf, features, b, cv=10)
scores

array([ 0.50966645,  0.5098789 ,  0.44374801,  0.58493573,  0.56868161,
        0.60089257,  0.57475295,  0.60408033,  0.56710233,  0.54425672])

In [18]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.55 (+/- 0.09)


In [19]:
from sklearn import svm
from sklearn.model_selection import cross_val_score
clf = MLPClassifier(alpha = 1)
scores = cross_val_score(clf, features, b, cv=10)
scores

array([ 0.40832802,  0.54695135,  0.51375757,  0.62658026,  0.59970254,
        0.46860057,  0.42758474,  0.69907555,  0.56731484,  0.6652853 ])

In [20]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
# using the neural network the accuracy is low

Accuracy: 0.55 (+/- 0.19)


In [21]:
from sklearn.model_selection import cross_val_score
clf = RandomForestClassifier(n_estimators = 18)
scores = cross_val_score(clf, features, b, cv=10)
scores

array([ 1.        ,  1.        ,  1.        ,  0.99989376,  1.        ,
        0.99978748,  1.        ,  1.        ,  1.        ,  0.99989374])

In [22]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
# Random forest has got very high accuracy rates

Accuracy: 1.00 (+/- 0.00)


In [23]:
from sklearn.model_selection import cross_val_score
clf = tree.DecisionTreeClassifier()
scores = cross_val_score(clf, features, b, cv=10)
scores

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [24]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
# Decision tree has produced very high accuracy rate

Accuracy: 1.00 (+/- 0.00)


In [25]:
from sklearn.model_selection import cross_val_score
clf = LogisticRegression()
scores = cross_val_score(clf, features, b, cv=10)
scores

array([ 0.92585511,  0.92054387,  0.91097418,  0.92064167,  0.92393498,
        0.92604399,  0.92466263,  0.93103815,  0.93326958,  0.93369461])

In [26]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
# Decision tree has produced very high accuracy rate
# A very good accuracy rate for 

Accuracy: 0.93 (+/- 0.01)


In [27]:
b.shape

(94122,)

In [28]:
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn.cross_validation import cross_val_predict
clf = GaussianNB()
#scores = cross_val_score(clf, features, b, cv=10)
#scores

from sklearn.metrics import classification_report
y_pred = cross_val_predict(clf, features, b, cv=10)
y_pred.shape
# generate report
print(classification_report(b, y_pred))

C:\Users\usmanzafar\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


             precision    recall  f1-score   support

          0       1.00      1.00      1.00     40995
          1       1.00      0.99      1.00     40002
          2       0.94      1.00      0.97      7130
          3       1.00      0.98      0.99      5995

avg / total       1.00      1.00      1.00     94122



In [29]:
clf = LogisticRegression()
clf = GaussianNB()
clf = tree.DecisionTreeClassifier()
clf = RandomForestClassifier(n_estimators = 18)
clf = MLPClassifier(alpha = 1)
clf = KNeighborsClassifier()
clf = SVC()
clf = GradientBoostingClassifier()

In [30]:
dict_classifiers = {
    "Logistic Regression": LogisticRegression(),
    "Nearest Neighbors": KNeighborsClassifier(),
    "Linear SVM": SVC(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
    "Decision Tree": tree.DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(n_estimators = 18),
    "Neural Net": MLPClassifier(alpha = 1),
    "Naive Bayes": GaussianNB()
}

In [31]:
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn.cross_validation import cross_val_predict
clf = tree.DecisionTreeClassifier()

from sklearn.metrics import classification_report
y_pred = cross_val_predict(clf, features, b, cv=2)
y_pred.shape
# generate report
print(classification_report(b, y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00     40995
          1       1.00      1.00      1.00     40002
          2       1.00      1.00      1.00      7130
          3       1.00      1.00      1.00      5995

avg / total       1.00      1.00      1.00     94122



In [32]:
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn.cross_validation import cross_val_predict
clf = MLPClassifier(alpha = 1)

from sklearn.metrics import classification_report
y_pred2 = cross_val_predict(clf, features, b, cv=10)
y_pred2.shape
# generate report
print(classification_report(b, y_pred2))

             precision    recall  f1-score   support

          0       0.65      0.66      0.65     40995
          1       0.53      0.61      0.56     40002
          2       0.26      0.11      0.16      7130
          3       0.19      0.13      0.15      5995

avg / total       0.54      0.56      0.55     94122



In [33]:
scores = cross_val_score(clf, features, b, cv=10,scoring='mean_squared_error')
scores

C:\Users\usmanzafar\Anaconda3\lib\site-packages\sklearn\metrics\scorer.py:100: DeprecationWarning: Scoring method mean_squared_error was renamed to neg_mean_squared_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)
C:\Users\usmanzafar\Anaconda3\lib\site-packages\sklearn\metrics\scorer.py:100: DeprecationWarning: Scoring method mean_squared_error was renamed to neg_mean_squared_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)
C:\Users\usmanzafar\Anaconda3\lib\site-packages\sklearn\metrics\scorer.py:100: DeprecationWarning: Scoring method mean_squared_error was renamed to neg_mean_squared_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)
C:\Users\usmanzafar\Anaconda3\lib\site-packages\sklearn\metrics\scorer.py:100: DeprecationWarning: Scoring method mean_squared_error was renamed to neg_mean_squared_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)
C:\Users\usm

array([-0.80592734, -1.98002974, -0.73154149, -0.67555508, -0.67417401,
       -0.74306662, -0.84475614, -0.51886091, -0.56370205, -0.62118797])

In [34]:
print("MSE: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

MSE: -0.82 (+/- 0.80)


In [35]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(b, y_pred2))


0.776343469115


In [36]:
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn.cross_validation import cross_val_predict
clf = GaussianNB()
#scores = cross_val_score(clf, features, b, cv=10)
#scores

from sklearn.metrics import classification_report
y_pred = cross_val_predict(clf, features, b, cv=10)
y_pred.shape

(94122,)

In [37]:
print(mean_squared_error(b, y_pred))
# In this case the mean squared error is very low

0.00472790633433


In [38]:
clf = GaussianNB()
y_pred = cross_val_predict(clf, features, b, cv=10)
y_pred.shape
print("The Mean squared error for Naive Bayes with Gaussian function with 10 cross folds validation! ")
print(mean_squared_error(b, y_pred))
print("")
print("The classification report for Naive Bayes with Gaussian function with 10 cross folds validation! ")
print(classification_report(b, y_pred))

The Mean squared error for Naive Bayes with Gaussian function with 10 cross folds validation! 
0.00472790633433

The classification report for Naive Bayes with Gaussian function with 10 cross folds validation! 
             precision    recall  f1-score   support

          0       1.00      1.00      1.00     40995
          1       1.00      0.99      1.00     40002
          2       0.94      1.00      0.97      7130
          3       1.00      0.98      0.99      5995

avg / total       1.00      1.00      1.00     94122



In [39]:
clf = LogisticRegression()
y_pred = cross_val_predict(clf, features, b, cv=10)
y_pred.shape
print("The Mean squared error for Logistic regression with 10 cross folds validation! ")
print(mean_squared_error(b, y_pred))
print("")
print("The classification report for Logistic Regression with 10 cross folds validation! ")
print(classification_report(b, y_pred))

The Mean squared error for Logistic regression with 10 cross folds validation! 
0.0841461082425

The classification report for Logistic Regression with 10 cross folds validation! 
             precision    recall  f1-score   support

          0       1.00      1.00      1.00     40995
          1       0.86      0.99      0.92     40002
          2       0.66      0.11      0.18      7130
          3       0.96      0.93      0.94      5995

avg / total       0.91      0.93      0.90     94122



In [40]:
clf = tree.DecisionTreeClassifier()
y_pred = cross_val_predict(clf, features, b, cv=10)
y_pred.shape
print("The Mean squared error for Decision tree with 10 cross folds validation!")
print(mean_squared_error(b, y_pred))
print("")
print("The classification report for decision tree with 10 cross folds validation !")
print(classification_report(b, y_pred))

The Mean squared error for Decision tree with 10 cross folds validation!
0.0

The classification report for decision tree with 10 cross folds validation !
             precision    recall  f1-score   support

          0       1.00      1.00      1.00     40995
          1       1.00      1.00      1.00     40002
          2       1.00      1.00      1.00      7130
          3       1.00      1.00      1.00      5995

avg / total       1.00      1.00      1.00     94122



In [41]:
clf = KNeighborsClassifier()
y_pred = cross_val_predict(clf, features, b, cv=10)
y_pred.shape
print("The Mean squared error for K Nearest Neighbor with 10 cross folds validation!")
print(mean_squared_error(b, y_pred))
print("")
print("The classification report for  K Nearest Neighbor with 10 cross folds validation! ")
print(classification_report(b, y_pred))
scores = cross_val_score(clf, features, b, cv=10)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

The Mean squared error for K Nearest Neighbor with 10 cross folds validation!
0.978910350396

The classification report for  K Nearest Neighbor with 10 cross folds validation! 
             precision    recall  f1-score   support

          0       0.55      0.66      0.60     40995
          1       0.57      0.57      0.57     40002
          2       0.49      0.22      0.30      7130
          3       0.28      0.10      0.14      5995

avg / total       0.54      0.55      0.54     94122

Accuracy: 0.55 (+/- 0.09)


In [42]:
clf = GradientBoostingClassifier()
y_pred = cross_val_predict(clf, features, b, cv=10)
y_pred.shape
print("The Mean squared error for Gradient Booster Classifier with 10 cross folds validation!")
print(mean_squared_error(b, y_pred))
print("")
print("The classification report for  Gradient Booster Classifier with 10 cross folds validation! ")
print(classification_report(b, y_pred))
scores = cross_val_score(clf, features, b, cv=10)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

The Mean squared error for Gradient Booster Classifier with 10 cross folds validation!
0.0

The classification report for  Gradient Booster Classifier with 10 cross folds validation! 
             precision    recall  f1-score   support

          0       1.00      1.00      1.00     40995
          1       1.00      1.00      1.00     40002
          2       1.00      1.00      1.00      7130
          3       1.00      1.00      1.00      5995

avg / total       1.00      1.00      1.00     94122

Accuracy: 1.00 (+/- 0.00)


In [43]:
from sklearn.svm import SVC
clf = RandomForestClassifier(n_estimators = 18)
y_pred = cross_val_predict(clf, features, b, cv=10)
y_pred.shape
print("The Mean squared error for Random Forest Classifier with 10 cross folds validation!")
print(mean_squared_error(b, y_pred))
print("")
print("The classification report for Random Forest Classifier with 10 cross folds validation! ")
print(classification_report(b, y_pred))
scores = cross_val_score(clf, features, b, cv=10)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

The Mean squared error for Random Forest Classifier with 10 cross folds validation!
8.49960689318e-05

The classification report for Random Forest Classifier with 10 cross folds validation! 
             precision    recall  f1-score   support

          0       1.00      1.00      1.00     40995
          1       1.00      1.00      1.00     40002
          2       1.00      1.00      1.00      7130
          3       1.00      1.00      1.00      5995

avg / total       1.00      1.00      1.00     94122

Accuracy: 1.00 (+/- 0.00)


In [44]:
clf = MLPClassifier(alpha = 1)
y_pred = cross_val_predict(clf, features, b, cv=10)
y_pred.shape
print("The Mean squared error for MLP with 10 cross folds validation! ")
print(mean_squared_error(b, y_pred))
print("")
print("The classification report for MLP with 10 cross folds validation! ")
print(classification_report(b, y_pred))
scores = cross_val_score(clf, features, b, cv=10)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

The Mean squared error for MLP with 10 cross folds validation! 
0.688744395572

The classification report for MLP with 10 cross folds validation! 
             precision    recall  f1-score   support

          0       0.71      0.71      0.71     40995
          1       0.59      0.61      0.60     40002
          2       0.21      0.20      0.21      7130
          3       0.27      0.23      0.25      5995

avg / total       0.59      0.60      0.60     94122

Accuracy: 0.55 (+/- 0.25)
